import streamlit as st
import pandas as pd
import plotly.express as px

# Page Config
st.set_page_config(
    page_title="Customer Dashboard",
    page_icon="📊",
    layout="wide"
)

# Load Data
df = pd.read_csv("notebooks/customer_segments.csv")

# Title
st.title("📊 Customer Dashboard")

st.write("Customer Intelligence & Marketing Analytics")

st.divider()

# ==========================
# KPI CARDS
# ==========================

total_customers = len(df)

vip_customers = len(df[df["Segment"] == "VIP Customer"])

loyal_customers = len(df[df["Segment"] == "Loyal Customer"])

inactive_customers = len(df[df["Segment"] == "Inactive Customer"])

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        label="Total Customers",
        value=total_customers
    )

with col2:
    st.metric(
        label="VIP Customers",
        value=vip_customers
    )

with col3:
    st.metric(
        label="Loyal Customers",
        value=loyal_customers
    )

with col4:
    st.metric(
        label="Inactive Customers",
        value=inactive_customers
    )

st.divider()

# ==========================
# SEGMENT DISTRIBUTION
# ==========================

st.subheader("Customer Segment Distribution")

fig = px.pie(               
    df,
    names="Segment",
    title="Customer Segments"
)
revenue = (
    df.groupby("Segment")["Monetary"]
      .sum()
      .sort_values(ascending=False)
)

st.bar_chart(revenue)

st.plotly_chart(
    fig,
    use_container_width=True
)

# ==========================
# REVENUE BY SEGMENT
# ==========================

st.subheader("Revenue By Segment")

revenue = (
    df.groupby("Segment")["Monetary"]
    .sum()
    .reset_index()
)

fig2 = px.bar(
    revenue,
    x="Segment",
    y="Monetary",
    title="Revenue Generated By Each Segment"
)

st.plotly_chart(
    fig2,
    use_container_width=True
)

# ==========================
# SEGMENT COUNTS
# ==========================

st.subheader("Customers Per Segment")

segment_count = (
    df["Segment"]
    .value_counts()
    .reset_index()
)

segment_count.columns = [
    "Segment",
    "Count"
]

st.dataframe(
    segment_count,
    use_container_width=True
)

# ==========================
# DATA PREVIEW
# ==========================

st.subheader("Customer Dataset")

st.dataframe(
    df.head(20),
    use_container_width=True
)